---
- name: install apache
  become: true
  ansible.builtin.yum:
    name: "httpd"
    state: present

- name: Start service httpd, if not started
  become: true
  ansible.builtin.service:
    name: httpd
    state: started

- name: install git
  become: true
  ansible.builtin.yum:
    name: "git"
    state: present

- name: clone a repo
  become: true
  ansible.builtin.git:
    repo: https://github.com/FrantzRenard/tooling.git
    dest: /var/www/html
    force: yes

- name: recursively remove /var/www/html/ directory
  become: true
  ansible.builtin.file:
    path: /var/www/html/
    state: absent
# tasks file for webserver